import type { Metadata } from "next";
import "../index.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Button } from "@mui/material";

export const metadata: Metadata = {
  title: "Film API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="wrapper">
          <div className="topbar">
            <Button variant='contained' href="/movies">movies</Button>
            <Button variant="contained" href="/people">People</Button>
          </div>
          <div className="content-centered">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
